# Generated by Django 2.2.17 on 2020-11-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Book',
            new_name='book',
        ),
    ]
