# Generated by Django 2.2.16 on 2020-10-12 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Book'),
            preserve_default=False,
        ),
    ]
