# Generated by Django 3.0.1 on 2020-10-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_member_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='%m/%d/%Y'),
        ),
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
