version: '3.6'

networks:
  sister:
    name: sister

# dial.up.4565

services:

  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./certs:/etc/nginx/certs

  # letsencrypt-nginx-proxy-companion:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #   volumes_from:
  #     - "nginx-proxy"

  wordpress:
    build: wordpress
    restart: always
    depends_on:
      - wordpress_db
    environment:
      WORDPRESS_DB_PASSWORD: dial.32
      WORDPRESS_DB_HOST: wordpress_db
      VIRTUAL_HOST: carve.d.jgleba.com
      LETSENCRYPT_HOST: carve.d.jgleba.com
      LETSENCRYPT_EMAIL: dgleba@gmail.com
      VIRTUAL_PORT: 80
      VIRTUAL_NETWORK: sister
    volumes:
      - ../sysdata/wordpress/www/html:/var/www/html
    ports:
      - 14123:80
    expose:
      - 80
    networks:
      - sister
      
  wordpress_db:
    image: mariadb
    restart: always
    volumes:
    #  - ./wordpress/data:/var/lib/mysql
      - wordpress_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dial.32
      MYSQL_DATABASE: wordpress
    networks:
      - sister

  adminer:
    # connect with something like 10.4.1.228:14117/  use compose service name or ip:port for server while logging in.
    image: adminer:4.7
    restart: always
    ports:
      - 14119:8080
    environment:
      - ADMINER_DEFAULT_SERVER=wordpress_db            
    networks:
      - sister

volumes:
  wordpress_data:




  